name: democab
description: A delivery app.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  persistent_bottom_nav_bar: ^3.1.0
  firebase_core : ^0.4.4+3
  firebase_auth: ^0.16.0
  firebase_database: ^3.1.5
  connectivity: ^2.0.0
  google_maps_flutter: ^0.5.28
  outline_material_icons: ^0.1.1
  geolocator: ^5.3.1
  http: ^0.12.1
  http_auth: ^0.3.1
  provider: ^4.1.2
  flutter_polyline_points: ^0.2.1
  font_awesome_flutter: ^8.8.1
  animated_text_kit: ^2.1.0
  flutter_geofire: ^1.0.3
  image_picker: ^0.6.4
  intl: ^0.16.0
  url_launcher: ^5.7.10
  splashscreen: ^1.3.3
  cached_network_image: ^2.3.3
  rave_flutter: ^0.0.9-alpha+2
  webview_flutter: ^0.3.22+1
  flutter_credit_card: ^0.1.3
  avatar_glow: ^1.2.0
  flutter_automation:
  speech_to_text: ^3.2.0
  shared_preferences: ^0.5.10
  assets_audio_player:
  toast:

  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_application_id: "^1.0.0"
  flutter_launcher_icons: "^0.8.0"
  flutter_native_splash: ^0.1.9
  flutter_test:
    sdk: flutter


dependency_overrides:
  flutter_application_id: ^1.0.0


flutter_icons:
  android: "icon"
  ios: true
  image_path: "assets/app_icon.png"

flutter_native_splash:
  image: "assets/splash_icon.png"
  color: "531690"
  

flutter_application_id:
  android:
    id: "so.aa"
    name: "SOA"
  ios:
    id: "so.aa"
    name: "SOA"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  
  fonts:
    - family: Brand-Bold
      fonts:
        - asset: fonts/bolt-semibold.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: Brand-Regular
      fonts:
        - asset: fonts/bolt-regular.ttf